### PR TITLE
Fix model switching and remove duplicate code

### LINKED ISSUE #1421: Links in profile view to models do not work in Juju 2.0
Go into the profile in a environment with multiple models and you'll notice that none of the 'Manage' links for the models work.

### PR DESCRIPTION
**Pull request by huwshimi**
Switching models from the user profile was not working as it was calling the wrong env switching code. As part of fixing this I also removed the duplicate switching methods. Fixes #1421.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- deploy this branch with Juju 2.0
- load the profile
- click on model
- click Manage
- the GUI should reload
- bonus points: try adding a second model and use the profile to switch between them

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4584/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4585/
Test PASSed.

**Comment by hatched** [comment]
When trying to create a new model in sandbox (not supported) I get the following error in the console:
```
Uncaught TypeError: this[(("handle" + data.Type) + data.Request)] is not a function
    receive @ combo?app/store/env/sandbox.js:246
```
Maybe we should disable that button entirely in sandbox mode? Or of course figure out why this branch introduced that error :)

**Comment by hatched** [comment]
QA :ok: in Juju 2.0

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4589/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4590/
Test PASSed.
